# Generated by Django 4.1.5 on 2023-01-23 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Competition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cname", models.CharField(max_length=40)),
                ("cdesc", models.CharField(max_length=200)),
                ("cdate", models.DateTimeField()),
                ("cvenue", models.CharField(max_length=200)),
                ("max_members", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="Request",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cname", models.CharField(max_length=40)),
                ("tname", models.CharField(max_length=40)),
                ("rmsge", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="TeamDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tname", models.CharField(max_length=40)),
                ("compe", models.CharField(max_length=40)),
                ("vacant_members", models.IntegerField(default=0)),
                ("tfref", models.BigIntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="TeamMembers",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tfref", models.BigIntegerField(default=0)),
                ("uname", models.BigIntegerField(default=0)),
                ("tbref", models.BigIntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uname", models.CharField(max_length=40)),
                ("upass", models.CharField(max_length=69)),
                ("umail", models.CharField(max_length=69)),
            ],
        ),
    ]
