# Generated by Django 4.1.5 on 2023-01-23 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("smartathon", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="competition",
            old_name="cdate",
            new_name="date",
        ),
        migrations.RenameField(
            model_name="competition",
            old_name="cdesc",
            new_name="description",
        ),
        migrations.RenameField(
            model_name="competition",
            old_name="cname",
            new_name="name",
        ),
        migrations.RenameField(
            model_name="competition",
            old_name="cvenue",
            new_name="venue",
        ),
        migrations.RenameField(
            model_name="request",
            old_name="cname",
            new_name="c_name",
        ),
        migrations.RenameField(
            model_name="request",
            old_name="rmsge",
            new_name="request_message",
        ),
        migrations.RenameField(
            model_name="request",
            old_name="tname",
            new_name="t_name",
        ),
        migrations.RenameField(
            model_name="teamdetails",
            old_name="compe",
            new_name="c_name",
        ),
        migrations.RenameField(
            model_name="teamdetails",
            old_name="tname",
            new_name="name",
        ),
        migrations.RenameField(
            model_name="teamdetails",
            old_name="tfref",
            new_name="team_member_id",
        ),
        migrations.RenameField(
            model_name="teammembers",
            old_name="tfref",
            new_name="team_member_id",
        ),
        migrations.RenameField(
            model_name="teammembers",
            old_name="tbref",
            new_name="team_member_id_back_referenced",
        ),
        migrations.RenameField(
            model_name="teammembers",
            old_name="uname",
            new_name="u_name",
        ),
        migrations.RenameField(
            model_name="user",
            old_name="umail",
            new_name="mail",
        ),
        migrations.RenameField(
            model_name="user",
            old_name="uname",
            new_name="name",
        ),
        migrations.RenameField(
            model_name="user",
            old_name="upass",
            new_name="password",
        ),
    ]
