# Generated by Django 4.1.5 on 2023-01-21 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("smartathon", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Competition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cname", models.CharField(max_length=40)),
                ("cdesc", models.CharField(max_length=200)),
                ("max_members", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="TeamDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tname", models.CharField(max_length=40)),
                ("cid", models.BigIntegerField(default=0)),
                ("members", models.IntegerField(default=0)),
                ("tfref", models.BigIntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="TeamMembers",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tfref", models.BigIntegerField(default=0)),
                ("uname", models.BigIntegerField(default=0)),
                ("tbref", models.BigIntegerField(null=True)),
            ],
        ),
        migrations.DeleteModel(
            name="Competitions",
        ),
        migrations.DeleteModel(
            name="Teams",
        ),
    ]
