# Generated by Django 4.1.5 on 2023-01-21 12:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("smartathon", "0002_competition_teamdetails_teammembers_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="competition",
            name="cdate",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 1, 21, 12, 10, 22, 620002, tzinfo=datetime.timezone.utc
                )
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="competition",
            name="cvenue",
            field=models.CharField(default="null venue", max_length=200),
            preserve_default=False,
        ),
    ]
