# Generated by Django 4.1.5 on 2023-01-21 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("smartathon", "0003_competition_cdate_competition_cvenue"),
    ]

    operations = [
        migrations.AddField(
            model_name="competition",
            name="cid",
            field=models.BigIntegerField(default=0),
        ),
    ]
